name: Publish Package

on:
  push:
    tags:
    - 'v+.[0-9]+.[0-9]+.[0-9]+'

jobs:
  build:
    env:
      API_KEY: ${{ secrets.API_KEY }}
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      # Setup .npmrc file to publish to npm
      - uses: actions/setup-go@v3
        with:
          go-version: '^1.19'

      - name: Get latest tag
        id: vars
        run: echo ::set-output name=tag::${GITHUB_REF:10}
      
      - name: Run tests
        run: go test . -v

      - name: List package
        run: GOPROXY=proxy.golang.org go list -m {{ vars.REGISTRY }}/{{ vars.ACTOR }}/{{ vars.pkg }}@{{ steps.var.outputs.tag }}